/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ProdukterRouteImport } from './routes/produkter'
import { Route as OmOssRouteImport } from './routes/om-oss'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SidaSlugRouteImport } from './routes/sida.$slug'
import { Route as CheckoutBekraftelseRouteImport } from './routes/checkout.bekraftelse'
import { Route as AdminSidorRouteImport } from './routes/admin.sidor'
import { Route as AdminProdukterRouteImport } from './routes/admin.produkter'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInnehallRouteImport } from './routes/admin.innehall'
import { Route as AdminChattRouteImport } from './routes/admin.chatt'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukterRoute = ProdukterRouteImport.update({
  id: '/produkter',
  path: '/produkter',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOssRoute = OmOssRouteImport.update({
  id: '/om-oss',
  path: '/om-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidaSlugRoute = SidaSlugRouteImport.update({
  id: '/sida/$slug',
  path: '/sida/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutBekraftelseRoute = CheckoutBekraftelseRouteImport.update({
  id: '/bekraftelse',
  path: '/bekraftelse',
  getParentRoute: () => CheckoutRoute,
} as any)
const AdminSidorRoute = AdminSidorRouteImport.update({
  id: '/sidor',
  path: '/sidor',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdukterRoute = AdminProdukterRouteImport.update({
  id: '/produkter',
  path: '/produkter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInnehallRoute = AdminInnehallRouteImport.update({
  id: '/innehall',
  path: '/innehall',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChattRoute = AdminChattRouteImport.update({
  id: '/chatt',
  path: '/chatt',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/faq': typeof FaqRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/produkter': typeof ProdukterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/chatt': typeof AdminChattRoute
  '/admin/innehall': typeof AdminInnehallRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/produkter': typeof AdminProdukterRoute
  '/admin/sidor': typeof AdminSidorRoute
  '/checkout/bekraftelse': typeof CheckoutBekraftelseRoute
  '/sida/$slug': typeof SidaSlugRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/faq': typeof FaqRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/produkter': typeof ProdukterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/chatt': typeof AdminChattRoute
  '/admin/innehall': typeof AdminInnehallRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/produkter': typeof AdminProdukterRoute
  '/admin/sidor': typeof AdminSidorRoute
  '/checkout/bekraftelse': typeof CheckoutBekraftelseRoute
  '/sida/$slug': typeof SidaSlugRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/faq': typeof FaqRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/produkter': typeof ProdukterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/chatt': typeof AdminChattRoute
  '/admin/innehall': typeof AdminInnehallRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/produkter': typeof AdminProdukterRoute
  '/admin/sidor': typeof AdminSidorRoute
  '/checkout/bekraftelse': typeof CheckoutBekraftelseRoute
  '/sida/$slug': typeof SidaSlugRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/faq'
    | '/kontakt'
    | '/om-oss'
    | '/produkter'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/chatt'
    | '/admin/innehall'
    | '/admin/login'
    | '/admin/produkter'
    | '/admin/sidor'
    | '/checkout/bekraftelse'
    | '/sida/$slug'
    | '/api/public/health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkout'
    | '/faq'
    | '/kontakt'
    | '/om-oss'
    | '/produkter'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/chatt'
    | '/admin/innehall'
    | '/admin/login'
    | '/admin/produkter'
    | '/admin/sidor'
    | '/checkout/bekraftelse'
    | '/sida/$slug'
    | '/api/public/health'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/faq'
    | '/kontakt'
    | '/om-oss'
    | '/produkter'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/chatt'
    | '/admin/innehall'
    | '/admin/login'
    | '/admin/produkter'
    | '/admin/sidor'
    | '/checkout/bekraftelse'
    | '/sida/$slug'
    | '/api/public/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRouteWithChildren
  FaqRoute: typeof FaqRoute
  KontaktRoute: typeof KontaktRoute
  OmOssRoute: typeof OmOssRoute
  ProdukterRoute: typeof ProdukterRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SidaSlugRoute: typeof SidaSlugRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkter': {
      id: '/produkter'
      path: '/produkter'
      fullPath: '/produkter'
      preLoaderRoute: typeof ProdukterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-oss': {
      id: '/om-oss'
      path: '/om-oss'
      fullPath: '/om-oss'
      preLoaderRoute: typeof OmOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sida/$slug': {
      id: '/sida/$slug'
      path: '/sida/$slug'
      fullPath: '/sida/$slug'
      preLoaderRoute: typeof SidaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/bekraftelse': {
      id: '/checkout/bekraftelse'
      path: '/bekraftelse'
      fullPath: '/checkout/bekraftelse'
      preLoaderRoute: typeof CheckoutBekraftelseRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/admin/sidor': {
      id: '/admin/sidor'
      path: '/sidor'
      fullPath: '/admin/sidor'
      preLoaderRoute: typeof AdminSidorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produkter': {
      id: '/admin/produkter'
      path: '/produkter'
      fullPath: '/admin/produkter'
      preLoaderRoute: typeof AdminProdukterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/innehall': {
      id: '/admin/innehall'
      path: '/innehall'
      fullPath: '/admin/innehall'
      preLoaderRoute: typeof AdminInnehallRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chatt': {
      id: '/admin/chatt'
      path: '/chatt'
      fullPath: '/admin/chatt'
      preLoaderRoute: typeof AdminChattRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminChattRoute: typeof AdminChattRoute
  AdminInnehallRoute: typeof AdminInnehallRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProdukterRoute: typeof AdminProdukterRoute
  AdminSidorRoute: typeof AdminSidorRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminChattRoute: AdminChattRoute,
  AdminInnehallRoute: AdminInnehallRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProdukterRoute: AdminProdukterRoute,
  AdminSidorRoute: AdminSidorRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CheckoutRouteChildren {
  CheckoutBekraftelseRoute: typeof CheckoutBekraftelseRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutBekraftelseRoute: CheckoutBekraftelseRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRouteWithChildren,
  FaqRoute: FaqRoute,
  KontaktRoute: KontaktRoute,
  OmOssRoute: OmOssRoute,
  ProdukterRoute: ProdukterRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SidaSlugRoute: SidaSlugRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
