/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ProdukterRouteImport } from './routes/produkter'
import { Route as OmOssRouteImport } from './routes/om-oss'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SidaSlugRouteImport } from './routes/sida.$slug'
import { Route as ProdukterSlugRouteImport } from './routes/produkter_.$slug'
import { Route as CheckoutBekraftelseRouteImport } from './routes/checkout.bekraftelse'
import { Route as AdminSidorRouteImport } from './routes/admin.sidor'
import { Route as AdminSakerhetRouteImport } from './routes/admin.sakerhet'
import { Route as AdminRabattkoderRouteImport } from './routes/admin.rabattkoder'
import { Route as AdminProdukterRouteImport } from './routes/admin.produkter'
import { Route as AdminOrdrarRouteImport } from './routes/admin.ordrar'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInnehallRouteImport } from './routes/admin.innehall'
import { Route as AdminDiagnostikRouteImport } from './routes/admin.diagnostik'
import { Route as AdminChattRouteImport } from './routes/admin.chatt'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicDiagClientRouteImport } from './routes/api/public/diag-client'
import { Route as ApiInternalNotifyRouteImport } from './routes/api/internal/notify'
import { Route as ApiInternalDiagRouteImport } from './routes/api/internal/diag'
import { Route as ApiDiscountValidateRouteImport } from './routes/api/discount.validate'
import { Route as ApiCryptoCreateInvoiceRouteImport } from './routes/api/crypto.create-invoice'
import { Route as ApiAdminProductImagesRouteImport } from './routes/api/admin/product-images'
import { Route as ApiPublicUploadsSplatRouteImport } from './routes/api/public/uploads.$'
import { Route as ApiPublicCryptoWebhookRouteImport } from './routes/api/public/crypto.webhook'
import { Route as ApiCryptoOrderOrderIdRouteImport } from './routes/api/crypto.order.$orderId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukterRoute = ProdukterRouteImport.update({
  id: '/produkter',
  path: '/produkter',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOssRoute = OmOssRouteImport.update({
  id: '/om-oss',
  path: '/om-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidaSlugRoute = SidaSlugRouteImport.update({
  id: '/sida/$slug',
  path: '/sida/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukterSlugRoute = ProdukterSlugRouteImport.update({
  id: '/produkter_/$slug',
  path: '/produkter/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutBekraftelseRoute = CheckoutBekraftelseRouteImport.update({
  id: '/bekraftelse',
  path: '/bekraftelse',
  getParentRoute: () => CheckoutRoute,
} as any)
const AdminSidorRoute = AdminSidorRouteImport.update({
  id: '/sidor',
  path: '/sidor',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSakerhetRoute = AdminSakerhetRouteImport.update({
  id: '/sakerhet',
  path: '/sakerhet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRabattkoderRoute = AdminRabattkoderRouteImport.update({
  id: '/rabattkoder',
  path: '/rabattkoder',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdukterRoute = AdminProdukterRouteImport.update({
  id: '/produkter',
  path: '/produkter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdrarRoute = AdminOrdrarRouteImport.update({
  id: '/ordrar',
  path: '/ordrar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInnehallRoute = AdminInnehallRouteImport.update({
  id: '/innehall',
  path: '/innehall',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiagnostikRoute = AdminDiagnostikRouteImport.update({
  id: '/diagnostik',
  path: '/diagnostik',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChattRoute = AdminChattRouteImport.update({
  id: '/chatt',
  path: '/chatt',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiagClientRoute = ApiPublicDiagClientRouteImport.update({
  id: '/api/public/diag-client',
  path: '/api/public/diag-client',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalNotifyRoute = ApiInternalNotifyRouteImport.update({
  id: '/api/internal/notify',
  path: '/api/internal/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalDiagRoute = ApiInternalDiagRouteImport.update({
  id: '/api/internal/diag',
  path: '/api/internal/diag',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscountValidateRoute = ApiDiscountValidateRouteImport.update({
  id: '/api/discount/validate',
  path: '/api/discount/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCryptoCreateInvoiceRoute = ApiCryptoCreateInvoiceRouteImport.update({
  id: '/api/crypto/create-invoice',
  path: '/api/crypto/create-invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminProductImagesRoute = ApiAdminProductImagesRouteImport.update({
  id: '/api/admin/product-images',
  path: '/api/admin/product-images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUploadsSplatRoute = ApiPublicUploadsSplatRouteImport.update({
  id: '/api/public/uploads/$',
  path: '/api/public/uploads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCryptoWebhookRoute = ApiPublicCryptoWebhookRouteImport.update({
  id: '/api/public/crypto/webhook',
  path: '/api/public/crypto/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCryptoOrderOrderIdRoute = ApiCryptoOrderOrderIdRouteImport.update({
  id: '/api/crypto/order/$orderId',
  path: '/api/crypto/order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/om-oss': typeof OmOssRoute
  '/produkter': typeof ProdukterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/chatt': typeof AdminChattRoute
  '/admin/diagnostik': typeof AdminDiagnostikRoute
  '/admin/innehall': typeof AdminInnehallRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/ordrar': typeof AdminOrdrarRoute
  '/admin/produkter': typeof AdminProdukterRoute
  '/admin/rabattkoder': typeof AdminRabattkoderRoute
  '/admin/sakerhet': typeof AdminSakerhetRoute
  '/admin/sidor': typeof AdminSidorRoute
  '/checkout/bekraftelse': typeof CheckoutBekraftelseRoute
  '/produkter/$slug': typeof ProdukterSlugRoute
  '/sida/$slug': typeof SidaSlugRoute
  '/api/admin/product-images': typeof ApiAdminProductImagesRoute
  '/api/crypto/create-invoice': typeof ApiCryptoCreateInvoiceRoute
  '/api/discount/validate': typeof ApiDiscountValidateRoute
  '/api/internal/diag': typeof ApiInternalDiagRoute
  '/api/internal/notify': typeof ApiInternalNotifyRoute
  '/api/public/diag-client': typeof ApiPublicDiagClientRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/crypto/order/$orderId': typeof ApiCryptoOrderOrderIdRoute
  '/api/public/crypto/webhook': typeof ApiPublicCryptoWebhookRoute
  '/api/public/uploads/$': typeof ApiPublicUploadsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/om-oss': typeof OmOssRoute
  '/produkter': typeof ProdukterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/chatt': typeof AdminChattRoute
  '/admin/diagnostik': typeof AdminDiagnostikRoute
  '/admin/innehall': typeof AdminInnehallRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/ordrar': typeof AdminOrdrarRoute
  '/admin/produkter': typeof AdminProdukterRoute
  '/admin/rabattkoder': typeof AdminRabattkoderRoute
  '/admin/sakerhet': typeof AdminSakerhetRoute
  '/admin/sidor': typeof AdminSidorRoute
  '/checkout/bekraftelse': typeof CheckoutBekraftelseRoute
  '/produkter/$slug': typeof ProdukterSlugRoute
  '/sida/$slug': typeof SidaSlugRoute
  '/api/admin/product-images': typeof ApiAdminProductImagesRoute
  '/api/crypto/create-invoice': typeof ApiCryptoCreateInvoiceRoute
  '/api/discount/validate': typeof ApiDiscountValidateRoute
  '/api/internal/diag': typeof ApiInternalDiagRoute
  '/api/internal/notify': typeof ApiInternalNotifyRoute
  '/api/public/diag-client': typeof ApiPublicDiagClientRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/crypto/order/$orderId': typeof ApiCryptoOrderOrderIdRoute
  '/api/public/crypto/webhook': typeof ApiPublicCryptoWebhookRoute
  '/api/public/uploads/$': typeof ApiPublicUploadsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/om-oss': typeof OmOssRoute
  '/produkter': typeof ProdukterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/chatt': typeof AdminChattRoute
  '/admin/diagnostik': typeof AdminDiagnostikRoute
  '/admin/innehall': typeof AdminInnehallRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/ordrar': typeof AdminOrdrarRoute
  '/admin/produkter': typeof AdminProdukterRoute
  '/admin/rabattkoder': typeof AdminRabattkoderRoute
  '/admin/sakerhet': typeof AdminSakerhetRoute
  '/admin/sidor': typeof AdminSidorRoute
  '/checkout/bekraftelse': typeof CheckoutBekraftelseRoute
  '/produkter_/$slug': typeof ProdukterSlugRoute
  '/sida/$slug': typeof SidaSlugRoute
  '/api/admin/product-images': typeof ApiAdminProductImagesRoute
  '/api/crypto/create-invoice': typeof ApiCryptoCreateInvoiceRoute
  '/api/discount/validate': typeof ApiDiscountValidateRoute
  '/api/internal/diag': typeof ApiInternalDiagRoute
  '/api/internal/notify': typeof ApiInternalNotifyRoute
  '/api/public/diag-client': typeof ApiPublicDiagClientRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/crypto/order/$orderId': typeof ApiCryptoOrderOrderIdRoute
  '/api/public/crypto/webhook': typeof ApiPublicCryptoWebhookRoute
  '/api/public/uploads/$': typeof ApiPublicUploadsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/kontakt'
    | '/llms.txt'
    | '/om-oss'
    | '/produkter'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/chatt'
    | '/admin/diagnostik'
    | '/admin/innehall'
    | '/admin/login'
    | '/admin/ordrar'
    | '/admin/produkter'
    | '/admin/rabattkoder'
    | '/admin/sakerhet'
    | '/admin/sidor'
    | '/checkout/bekraftelse'
    | '/produkter/$slug'
    | '/sida/$slug'
    | '/api/admin/product-images'
    | '/api/crypto/create-invoice'
    | '/api/discount/validate'
    | '/api/internal/diag'
    | '/api/internal/notify'
    | '/api/public/diag-client'
    | '/api/public/health'
    | '/api/crypto/order/$orderId'
    | '/api/public/crypto/webhook'
    | '/api/public/uploads/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkout'
    | '/kontakt'
    | '/llms.txt'
    | '/om-oss'
    | '/produkter'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/chatt'
    | '/admin/diagnostik'
    | '/admin/innehall'
    | '/admin/login'
    | '/admin/ordrar'
    | '/admin/produkter'
    | '/admin/rabattkoder'
    | '/admin/sakerhet'
    | '/admin/sidor'
    | '/checkout/bekraftelse'
    | '/produkter/$slug'
    | '/sida/$slug'
    | '/api/admin/product-images'
    | '/api/crypto/create-invoice'
    | '/api/discount/validate'
    | '/api/internal/diag'
    | '/api/internal/notify'
    | '/api/public/diag-client'
    | '/api/public/health'
    | '/api/crypto/order/$orderId'
    | '/api/public/crypto/webhook'
    | '/api/public/uploads/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/kontakt'
    | '/llms.txt'
    | '/om-oss'
    | '/produkter'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/chatt'
    | '/admin/diagnostik'
    | '/admin/innehall'
    | '/admin/login'
    | '/admin/ordrar'
    | '/admin/produkter'
    | '/admin/rabattkoder'
    | '/admin/sakerhet'
    | '/admin/sidor'
    | '/checkout/bekraftelse'
    | '/produkter_/$slug'
    | '/sida/$slug'
    | '/api/admin/product-images'
    | '/api/crypto/create-invoice'
    | '/api/discount/validate'
    | '/api/internal/diag'
    | '/api/internal/notify'
    | '/api/public/diag-client'
    | '/api/public/health'
    | '/api/crypto/order/$orderId'
    | '/api/public/crypto/webhook'
    | '/api/public/uploads/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRouteWithChildren
  KontaktRoute: typeof KontaktRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  OmOssRoute: typeof OmOssRoute
  ProdukterRoute: typeof ProdukterRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProdukterSlugRoute: typeof ProdukterSlugRoute
  SidaSlugRoute: typeof SidaSlugRoute
  ApiAdminProductImagesRoute: typeof ApiAdminProductImagesRoute
  ApiCryptoCreateInvoiceRoute: typeof ApiCryptoCreateInvoiceRoute
  ApiDiscountValidateRoute: typeof ApiDiscountValidateRoute
  ApiInternalDiagRoute: typeof ApiInternalDiagRoute
  ApiInternalNotifyRoute: typeof ApiInternalNotifyRoute
  ApiPublicDiagClientRoute: typeof ApiPublicDiagClientRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiCryptoOrderOrderIdRoute: typeof ApiCryptoOrderOrderIdRoute
  ApiPublicCryptoWebhookRoute: typeof ApiPublicCryptoWebhookRoute
  ApiPublicUploadsSplatRoute: typeof ApiPublicUploadsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkter': {
      id: '/produkter'
      path: '/produkter'
      fullPath: '/produkter'
      preLoaderRoute: typeof ProdukterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-oss': {
      id: '/om-oss'
      path: '/om-oss'
      fullPath: '/om-oss'
      preLoaderRoute: typeof OmOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sida/$slug': {
      id: '/sida/$slug'
      path: '/sida/$slug'
      fullPath: '/sida/$slug'
      preLoaderRoute: typeof SidaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkter_/$slug': {
      id: '/produkter_/$slug'
      path: '/produkter/$slug'
      fullPath: '/produkter/$slug'
      preLoaderRoute: typeof ProdukterSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/bekraftelse': {
      id: '/checkout/bekraftelse'
      path: '/bekraftelse'
      fullPath: '/checkout/bekraftelse'
      preLoaderRoute: typeof CheckoutBekraftelseRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/admin/sidor': {
      id: '/admin/sidor'
      path: '/sidor'
      fullPath: '/admin/sidor'
      preLoaderRoute: typeof AdminSidorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sakerhet': {
      id: '/admin/sakerhet'
      path: '/sakerhet'
      fullPath: '/admin/sakerhet'
      preLoaderRoute: typeof AdminSakerhetRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rabattkoder': {
      id: '/admin/rabattkoder'
      path: '/rabattkoder'
      fullPath: '/admin/rabattkoder'
      preLoaderRoute: typeof AdminRabattkoderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produkter': {
      id: '/admin/produkter'
      path: '/produkter'
      fullPath: '/admin/produkter'
      preLoaderRoute: typeof AdminProdukterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ordrar': {
      id: '/admin/ordrar'
      path: '/ordrar'
      fullPath: '/admin/ordrar'
      preLoaderRoute: typeof AdminOrdrarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/innehall': {
      id: '/admin/innehall'
      path: '/innehall'
      fullPath: '/admin/innehall'
      preLoaderRoute: typeof AdminInnehallRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/diagnostik': {
      id: '/admin/diagnostik'
      path: '/diagnostik'
      fullPath: '/admin/diagnostik'
      preLoaderRoute: typeof AdminDiagnostikRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chatt': {
      id: '/admin/chatt'
      path: '/chatt'
      fullPath: '/admin/chatt'
      preLoaderRoute: typeof AdminChattRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/diag-client': {
      id: '/api/public/diag-client'
      path: '/api/public/diag-client'
      fullPath: '/api/public/diag-client'
      preLoaderRoute: typeof ApiPublicDiagClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/notify': {
      id: '/api/internal/notify'
      path: '/api/internal/notify'
      fullPath: '/api/internal/notify'
      preLoaderRoute: typeof ApiInternalNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/diag': {
      id: '/api/internal/diag'
      path: '/api/internal/diag'
      fullPath: '/api/internal/diag'
      preLoaderRoute: typeof ApiInternalDiagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discount/validate': {
      id: '/api/discount/validate'
      path: '/api/discount/validate'
      fullPath: '/api/discount/validate'
      preLoaderRoute: typeof ApiDiscountValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crypto/create-invoice': {
      id: '/api/crypto/create-invoice'
      path: '/api/crypto/create-invoice'
      fullPath: '/api/crypto/create-invoice'
      preLoaderRoute: typeof ApiCryptoCreateInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/product-images': {
      id: '/api/admin/product-images'
      path: '/api/admin/product-images'
      fullPath: '/api/admin/product-images'
      preLoaderRoute: typeof ApiAdminProductImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/uploads/$': {
      id: '/api/public/uploads/$'
      path: '/api/public/uploads/$'
      fullPath: '/api/public/uploads/$'
      preLoaderRoute: typeof ApiPublicUploadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crypto/webhook': {
      id: '/api/public/crypto/webhook'
      path: '/api/public/crypto/webhook'
      fullPath: '/api/public/crypto/webhook'
      preLoaderRoute: typeof ApiPublicCryptoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crypto/order/$orderId': {
      id: '/api/crypto/order/$orderId'
      path: '/api/crypto/order/$orderId'
      fullPath: '/api/crypto/order/$orderId'
      preLoaderRoute: typeof ApiCryptoOrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminChattRoute: typeof AdminChattRoute
  AdminDiagnostikRoute: typeof AdminDiagnostikRoute
  AdminInnehallRoute: typeof AdminInnehallRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrdrarRoute: typeof AdminOrdrarRoute
  AdminProdukterRoute: typeof AdminProdukterRoute
  AdminRabattkoderRoute: typeof AdminRabattkoderRoute
  AdminSakerhetRoute: typeof AdminSakerhetRoute
  AdminSidorRoute: typeof AdminSidorRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminChattRoute: AdminChattRoute,
  AdminDiagnostikRoute: AdminDiagnostikRoute,
  AdminInnehallRoute: AdminInnehallRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOrdrarRoute: AdminOrdrarRoute,
  AdminProdukterRoute: AdminProdukterRoute,
  AdminRabattkoderRoute: AdminRabattkoderRoute,
  AdminSakerhetRoute: AdminSakerhetRoute,
  AdminSidorRoute: AdminSidorRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CheckoutRouteChildren {
  CheckoutBekraftelseRoute: typeof CheckoutBekraftelseRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutBekraftelseRoute: CheckoutBekraftelseRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRouteWithChildren,
  KontaktRoute: KontaktRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  OmOssRoute: OmOssRoute,
  ProdukterRoute: ProdukterRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProdukterSlugRoute: ProdukterSlugRoute,
  SidaSlugRoute: SidaSlugRoute,
  ApiAdminProductImagesRoute: ApiAdminProductImagesRoute,
  ApiCryptoCreateInvoiceRoute: ApiCryptoCreateInvoiceRoute,
  ApiDiscountValidateRoute: ApiDiscountValidateRoute,
  ApiInternalDiagRoute: ApiInternalDiagRoute,
  ApiInternalNotifyRoute: ApiInternalNotifyRoute,
  ApiPublicDiagClientRoute: ApiPublicDiagClientRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiCryptoOrderOrderIdRoute: ApiCryptoOrderOrderIdRoute,
  ApiPublicCryptoWebhookRoute: ApiPublicCryptoWebhookRoute,
  ApiPublicUploadsSplatRoute: ApiPublicUploadsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
